// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type About = Collections['about']['schema']['_output']
export declare const about: About[]
